package com.assesment.githubuser.constant

object WorkerConstant {
    const val WORKER_NAME_CACHED_SEARCH = "WORKER_NAME_CACHED_SEARCH"
    const val KEY_CACHED_SEARCH_USER_WORKER = "KEY_CACHED_SEARCH_USER_WORKER"
    const val KEY_CACHED_SEARCH_QUERY_WORKER = "KEY_CACHED_SEARCH_QUERY_WORKER"
    const val KEY_CACHED_USER_DETAIL_WORKER = "KEY_CACHED_USER_DETAIL_WORKER"
}